apiVersion: jenkins.io/v1
kind: PipelineActivity
metadata:
  annotations:
    lighthouse.jenkins-x.io/cloneURI: https://github.com/jstrachan/nodey510.git
    lighthouse.jenkins-x.io/job: release
  creationTimestamp: "2020-09-25T08:19:02Z"
  generation: 2
  labels:
    branch: master
    build: 8vqh9
    created-by-lighthouse: "true"
    event-GUID: fa415776-ff00-11ea-86f1-f1ab7dba0de0
    lighthouse.jenkins-x.io/baseSHA: 05bb4876fc299ac47c84d675d975bdcfb14ad39e
    lighthouse.jenkins-x.io/branch: master
    lighthouse.jenkins-x.io/buildNum: "1601019026059"
    lighthouse.jenkins-x.io/context: release
    lighthouse.jenkins-x.io/id: fac307f4-ff00-11ea-a3f9-decc2331f53d
    lighthouse.jenkins-x.io/job: release
    lighthouse.jenkins-x.io/lastCommitSHA: 05bb4876fc299ac47c84d675d975bdcfb14ad39e
    lighthouse.jenkins-x.io/refs.org: jstrachan
    lighthouse.jenkins-x.io/refs.repo: nodey510
    lighthouse.jenkins-x.io/type: postsubmit
    owner: jstrachan
    podName: release-b4849-from-build-pack-fxf4x-pod-zklbs
    provider: github
    repository: nodey510
    tekton.dev/pipeline: release-b4849
  name: jstrachan-nodey510-master-8vqh9
  namespace: jx
  resourceVersion: "5735853"
  selfLink: /apis/jenkins.io/v1/namespaces/jx/pipelineactivities/jstrachan-nodey510-master-8vqh9
  uid: 1d63ddde-f8ac-40ca-a6bc-be0ecf798e09
spec:
  baseSHA: 05bb4876fc299ac47c84d675d975bdcfb14ad39e
  batchPipelineActivity: {}
  build: 8vqh9
  context: release
  gitBranch: master
  gitOwner: jstrachan
  gitRepository: nodey510
  gitUrl: https://github.com/jstrachan/nodey510.git
  lastCommitMessage: |
    fix: use latest promote
  lastCommitSHA: a8861fd995de349cab52376cd857ca296363cfe1
  pipeline: jstrachan/nodey510/master
  releaseNotesURL: https://github.com/jstrachan/nodey510/releases/tag/v0.0.1
  status: Failed
  steps:
  - kind: Stage
    stage:
      name: from build pack
      status: Failed
      steps:
      - name: Git Clone
        status: Succeeded
      - name: Git Setup
        status: Succeeded
      - name: Next Version
        status: Succeeded
      - name: Tag Version
        status: Succeeded
      - name: Setup Builder Home
        status: Succeeded
      - name: Git Merge
        status: Succeeded
      - name: Jx Variables
        status: Succeeded
      - name: Build Npmrc
        status: Succeeded
      - name: Build Npm Install
        status: Succeeded
      - name: Build Npm Test
        status: Succeeded
      - name: Build Container Build
        status: Succeeded
      - name: Promote Changelog
        status: Succeeded
      - name: Promote Helm Release
        status: Succeeded
      - name: Promote Jx Promote
        status: Failed
  - kind: Promote
    promote:
      environment: staging
      pullRequest:
        pullRequestURL: https://github.com/jstrachan/jx3-demo-catalog-dev/pull/12
        startedTimestamp: "2020-09-25T08:19:12Z"
        status: Running
      status: Running
  version: 0.0.1
status: {}
