apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx
      changes:
        - regex:
            pattern: |
              \s+PipelineVersion = "(.*)"
            files:
              - "pkg/plugins/versions.go"
    - changes:
      - regex:
          pattern: |
            github.com/jenkins-x-plugins/jx-pipeline v(.*)
          files:
          - "go.mod"
      - go:
          owner:
          - jenkins-x-plugins
          repositories:
            include:
            - jx-build-controller
          package: github.com/jenkins-x-plugins/jx-pipeline
          upgradePackages:
            include:
            - "github.com/jenkins-x/*"
            - "github.com/jenkins-x-plugins/*"
