apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
    - urls:
        - https://github.com/jenkins-x/jx-cli
      changes:
        - regex:
            pattern: |
              \s+PipelineVersion = "(.*)"
            files:
              - "pkg/plugins/versions.go"
    - urls:
        - https://github.com/jenkinsci/tekton-client-plugin
      changes:
        - regex:
            pattern: |
              \s+<jx-pipeline\.version>(.*)<\/jx-pipeline\.version>
            files:
              - "pom.xml"
